name: 'Release on PyPi'
on:
  push:
    branches:
    - main
    - sandbox
    paths:
    - /src/**/*
  workflow_dispatch:

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install requirements
      run: | 
        pip install wheel==0.42.0
        pip install twine==4.0.2
        pip install setuptools==65.5.0
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Check package
      run: twine check dist/*
    - name: Check package
      run: twine check dist/*
    - name: Publish
      run: twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u ${{ secrets.PYPI_USER }} -p '${{ secrets.PYPI_PASSWORD }}'